environment:
  matrix:
    - nodejs_version: "7.0"
    - nodejs_version: "7.4"
    - nodejs_version: "7.5"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - node --version
  - npm --version
  - npm run lint
  - npm run test:security
  - npm run test:code
build: off